import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function StudioServices() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aliv Cinema - Studio Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>
      Studio Services
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://teraret.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/teraret.svg" alt="Teraret Logo" width={83} height={29} />
          </span>
          
        </a>
      </footer>
    </div>
  )
}
