import Head from 'next/head'
import Image from 'next/image'
import CardTemplateUrl from '../../src/CardTemplateUrl'
import Grid from '@mui/material/Grid';
import {ServerUrl} from './../../src/config'

export default function BusinessServices() {
  return (
    <div>
      <Head>
        <title>Aliv Cinema - Business Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1>
      Business Service
        </h1>
        <p>
        We are Aliv Cinema.We are Team of cinephile focused on a mission of releasing best in class Movies in both Online and Offline.
        </p>

       <p> Our Team:-</p>
       <Grid container spacing={2}>
       <Grid item xs={4}>
       <CardTemplateUrl name="OTT Consulting" url={ServerUrl+"business-services/ott-consulting"} />
       </Grid>
       <Grid item xs={4}>
       <CardTemplateUrl  name="Advertisement" url={ServerUrl+"business-services/advertisement"} />
       </Grid>
       </Grid>
      </main>
    </div>
  )
}
