import Head from 'next/head'
import Image from 'next/image'
import CardTemplate from '../src/CardTemplate'
import Grid from '@mui/material/Grid';

export default function AboutUs() {
  return (
    <div>
      <Head>
        <title>Aliv Cinema - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1>
      About Us
        </h1>
        <p>
        We are Aliv Cinema.We are Team of cinephile focused on a mission of releasing best in class Movies in both Online and Offline.
        </p>

       <p> Our Team:-</p>
       <Grid container spacing={2}>
       <Grid item xs={4}>
       <CardTemplate name ="Harish Babu B K" about="Harish is a Web Developer By Profession and Filmaker by passion.Harish has good amount of experience designing websites and Advertisement Strategy" skills="Photoshop,Website Designing,Digital Marketing,Direction"/>
       </Grid>
       <Grid item xs={4}>
       <CardTemplate name ="Praveen Rehan Duraisamy" about="Praveen is a Cinematographer by Profession and has got degree in Cinematography from Australia.He has worked in good amount of Fashon Photography assignments, Short Films and Advertisements." skills="Photography,Cinematography,Direction"/>
       </Grid>
       <Grid item xs={4}>
       <CardTemplate name ="Pavithran Arjunan" about="Pavithran  is a Cinematographer by Profession.He has worked in good amount of Wildlife Photography assignments,National Geography Film assignment, Short Films,  and Advertisements." skills="Photography,Cinematography,Direction"/>
       </Grid>
       <Grid item xs={4}>
       <CardTemplate name ="K Mani Maran" about="Mani is a Editor by Profession.He has worked in good amount of Short Films,  and Advertisements." skills="Editing ,Color Correction,Direction"/>
       </Grid>
       <Grid item xs={4}>
       <CardTemplate name ="Manghesh" about="Manghesh is a Music Director by Profession.He has good experience composing for AD Jingles and Short Film" skills="Music Composing"/>

       </Grid>




       </Grid>
      </main>
    </div>
  )
}
