import * as React from 'react';
import Head from 'next/head'
import AppBar from '@mui/material/AppBar';
import Button from '@mui/material/Button';
import CameraIcon from '@mui/icons-material/PhotoCamera';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import CssBaseline from '@mui/material/CssBaseline';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Link from '@mui/material/Link';
import Chip from '@mui/material/Chip';
import { createTheme, ThemeProvider } from '@mui/material/styles';

function Copyright() {
  return (
    <Typography variant="body2" color="text.secondary" align="center">
      {'Copyright © '}
      <Link color="inherit" href="https://mui.com/">
        Your Website
      </Link>{' '}
      {new Date().getFullYear()}
      {'.'}
    </Typography>
  );
}

const cards = [{"id":1,"title":"Harish Babu B K","content":"Harish is a Web Developer By Profession and Filmaker by passion.Harish has good amount of experience designing websites and Advertisement Strategy","skills":["Photoshop","Website Designing","Digital Marketing"]},
               {"id":2,"title":"Praveen Rehan Duraisamy","content":"Praveen is a Cinematographer by Profession and has got degree in Cinematography from Australia.He has worked in good amount of Fashon Photography assignments, Short Films and Advertisements.","skills":["Photography","Cinematography","Direction"]},
               {"id":3,"title":"Pavithran Arjunan","content":"Pavithran is a Cinematographer by Profession.He has worked in good amount of Wildlife Photography assignments,National Geography Film assignment, Films, and Advertisements.","skills":["Photography","Cinematography","Direction"]},
               {"id":4,"title":"K Mani Maran","content":"Mani is a Editor by Profession.He has worked in good amount of Short Films, and Advertisements.","skills":["Editing" ,"Color Correction","Direction"]},
               {"id":5,"title":"Manghesh","content":"Manghesh is a Music Director by Profession.He has good experience composing for AD Jingles and Short Film.","skills":["Music Composing"]}];


const theme = createTheme();

export default function Album() {
  return (<div>
    <Head>
    <title>Aliv Cinema - About Us</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
    <ThemeProvider theme={theme}>
      <CssBaseline />
        {/* Hero unit */}
        <Box
          sx={{
            bgcolor: 'background.paper',
            pt: 8,
            pb: 6,
          }}
        >
          <Container maxWidth="sm">
            <Typography
              component="h1"
              variant="h2"
              align="center"
              color="text.primary"
              gutterBottom
            >
              About Us
            </Typography>
            <Typography variant="h5" align="center" color="text.secondary" paragraph>
            We are Aliv Cinema.We are Team of cinephile focused on a mission of releasing best in class Movies in both Online and Offline.
            </Typography>
          </Container>
        </Box>
        <Container sx={{ py: 8 }} maxWidth="md">
          {/* End hero unit */}
          <Grid container spacing={4}>
            {cards.map((card) => (
              <Grid item key={card.id} xs={12} sm={6} xl={2}>
                <Card
                  sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}
                >
                    <CardHeader
        title={card.title}
      />
                  <CardMedia
                    component="img"
                    sx={{
                      // 16:9
                      pt: '56.25%',
                    }}
                    image="https://source.unsplash.com/random"
                    alt="random"
                  />
                  <CardContent sx={{ flexGrow: 1 }}>
                    <Typography>
                    {card.content}
                    </Typography>
                  </CardContent>
                  <CardActions>
                    {card.skills.map((skill) => (<><Chip label={skill} variant="outlined" /></>))}
                  </CardActions>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      {/* Footer */}
      <Box sx={{ bgcolor: 'background.paper', p: 6 }} component="footer">
        <Typography variant="h6" align="center" gutterBottom>
          Footer
        </Typography>
        <Typography
          variant="subtitle1"
          align="center"
          color="text.secondary"
          component="p"
        >
          Something here to give the footer a purpose!
        </Typography>
        <Copyright />
      </Box>
      {/* End footer */}
    </ThemeProvider>
    </main>
    </div>);
}