import Head from 'next/head'
import Image from 'next/image'
import CardTemplateUrl from '../src/CardTemplateUrl'
import Grid from '@mui/material/Grid';
import {ServerUrl} from '../src/config'
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';


export default function BusinessServices() {
  return (
    <div>
      <Head>
        <title>Aliv Cinema - App - Platform </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Container disableGutters maxWidth="sm" component="main" sx={{ pt: 8, pb: 6 }}>
        <Typography
          component="h1"
          variant="h2"
          align="center"
          color="text.primary"
          gutterBottom
        >
          Business Service
        </Typography>
      </Container>
      <Container maxWidth="md" component="main">
       <Grid container spacing={2}>
       <Grid item xs={4}>
       {/* <MediaControlCardUrl title="OTT Consulting" description="Play Button to Know More" /> */}
       <CardTemplateUrl name="OTT Consulting" url={ServerUrl+"business-services/ott-consulting"} />
       </Grid>
       <Grid item xs={4}>
       {/* <MediaControlCardUrl title="Advertisement" description="Play Button to Know More"  /> */}
       <CardTemplateUrl  name="Advertisement" url={ServerUrl+"business-services/advertisement"} />
       </Grid>
       </Grid>
       </Container>
      </main>
    </div>
  )
}